//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
** Karpenter Provider OCI
**
** Copyright (c) 2026 Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetwork) DeepCopyInto(out *NativePodNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetwork.
func (in *NativePodNetwork) DeepCopy() *NativePodNetwork {
	if in == nil {
		return nil
	}
	out := new(NativePodNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NativePodNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetworkList) DeepCopyInto(out *NativePodNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NativePodNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetworkList.
func (in *NativePodNetworkList) DeepCopy() *NativePodNetworkList {
	if in == nil {
		return nil
	}
	out := new(NativePodNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NativePodNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetworkSpec) DeepCopyInto(out *NativePodNetworkSpec) {
	*out = *in
	if in.NetworkSecurityGroupIDs != nil {
		in, out := &in.NetworkSecurityGroupIDs, &out.NetworkSecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodSubnetIDs != nil {
		in, out := &in.PodSubnetIDs, &out.PodSubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetworkSpec.
func (in *NativePodNetworkSpec) DeepCopy() *NativePodNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NativePodNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativePodNetworkStatus) DeepCopyInto(out *NativePodNetworkStatus) {
	*out = *in
	if in.VNICs != nil {
		in, out := &in.VNICs, &out.VNICs
		*out = make([]VNIC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativePodNetworkStatus.
func (in *NativePodNetworkStatus) DeepCopy() *NativePodNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NativePodNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VNIC) DeepCopyInto(out *VNIC) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VNIC.
func (in *VNIC) DeepCopy() *VNIC {
	if in == nil {
		return nil
	}
	out := new(VNIC)
	in.DeepCopyInto(out)
	return out
}
